---
- name: Add technical user to Grafana
  hosts: localhost
  tasks:
    - name: Wait for Grafana to start
      uri:
        url: "${GRAFANA_URL}/api/health"
        method: GET
        status_code: 200
      retries: 10
      delay: 5

    - name: Add technical user with token
      uri:
        url: "${GRAFANA_URL}/api/auth/keys"
        method: POST
        headers:
          Authorization: "Bearer {{ ${GRAFANA_TOKEN} }}"
        body: "{{ lookup('file', '/ansible/technical_user.json') }}"
        status_code: 200
        return_content: yes
      register: response

    - debug:
        msg: "Response: {{ response }}"
