version: '3.8'
name: Telegram_Grafana_Report_bot
services:

  telegram_grafana_report_bot:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    container_name: Telegram_Grafana_Report_Bot
    volumes:
      - ../Source_code:/application/Source_code
      - ../config.json:/application/temporary_config.json:rw
      - ./requirements.txt:/requirements.txt
    environment:
      # Telegram settings:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}

      # Bot white lists:
      - TELEGRAM_BOT_DM_WHITE_LIST=${TELEGRAM_BOT_DM_WHITE_LIST}
      - TELEGRAM_BOT_CHANNEL_WHITE_LIST=${TELEGRAM_BOT_CHANNEL_WHITE_LIST}

      # Grafana settings:
      - GRAFANA_URL=${GRAFANA_URL}
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
    networks:
      - external_network
      - grafana_network
    ports:
      - "8443:8443"
      - "443:443"
      - "80:80"
    restart: always

  example_grafana:
    image: grafana/grafana:11.2.2
    platform: linux/amd64
    container_name: Example_Grafana
    depends_on:
      - grafana_renderer
    ports:
      - "3000:3000"
    networks:
      - grafana_network
    environment:
      # Grafana url settings:
      - GF_SERVER_DOMAIN=example_grafana

      # Grafana Redner settings:
      - GF_RENDERING_SERVER_URL=${GRAFANA_RENDER_SERVER_URL}
      - GF_RENDERING_CALLBACK_URL=${GRAFANA_URL}

      # Admin user credentials:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

      # Dashboards in persistent storage:
      - GF_DASHBOARDS_JSON_ENABLED=true

      # Security policy:
      - GF_AUTH_TOKEN_AUTH_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=true
    volumes:
      - grafana_persistent_storage:/var/lib/grafana
      - ../Grafana/dashboards:/var/lib/grafana/dashboards
      - ../Grafana/dashboards_setting.yaml:/etc/grafana/provisioning/dashboards/dashboards_setting.yaml
    restart: always

  grafana_renderer:
    container_name: Grafana_Image_Renderer
    image: grafana/grafana-image-renderer:3.11.5
    ports:
      - "8081:8081"
    networks:
      - grafana_network
    environment:
      - ENABLE_METRICS=true
      - RENDERER_ARGS="--no-sandbox"
    restart: always

volumes:
  grafana_persistent_storage:

networks:
  external_network:
    driver: bridge
  grafana_network: